services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: verve
      MYSQL_DATABASE: verve
      MYSQL_USER: verve
      MYSQL_PASSWORD: verve
  broker:
    image: apache/kafka:latest
    container_name: broker
    ports:
      - "9092:9092"